name: Arquillian Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  wildfly-integration:
    name: 'WildFly Integration Tests'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        java:
          - 17
          - 21

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven
      - name: Build with Maven Java ${{ matrix.java }} - ${{ matrix.os }}
        run:  |
          ./mvnw -V clean install -U -B -fae '-Pwildfly' '-T1' '-Pintegration-tests'
      - uses: actions/upload-artifact@v6
        if: failure()
        with:
          name: ${{ matrix.os }}-${{ matrix.java }}-wildfly-surefire-reports
          path: '**/surefire-reports/*'
      - uses: actions/upload-artifact@v6
        if: failure()
        with:
          name: ${{ matrix.os }}-${{ matrix.java }}-wildfly-server-logs
          path: '**/server.log'

  payara-integration:
    name: 'Payara ${{ matrix.payara }} Integration Tests (${{ matrix.os }}, ${{ matrix.java }})'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        java:
          - 11
          - 17
          - 21
        payara:
          - 6
          - 7
        exclude:
          # Payara 7 requires JDK 21+ (compiled with class file version 65)
          - java: 11
            payara: 7
          - java: 17
            payara: 7

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven
      - name: Build with Maven Java ${{ matrix.java }} - Payara ${{ matrix.payara }} - ${{ matrix.os }}
        run:  |
          ./mvnw -V clean install -U -B -fae '-Dpayara.version=${{ matrix.payara }}' '-T1' '-Pintegration-tests'
      - uses: actions/upload-artifact@v6
        if: failure()
        with:
          name: ${{ matrix.os }}-${{ matrix.java }}-payara-${{ matrix.payara }}-surefire-reports
          path: '**/surefire-reports/*'
      - uses: actions/upload-artifact@v6
        if: failure()
        with:
          name: ${{ matrix.os }}-${{ matrix.java }}-payara-${{ matrix.payara }}-server-logs
          path: '**/server.log'
