# This workflow will build a Java project with Maven
# For more information see: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Arquillian Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * *' # Every day at 00:00 UTC

# Only run the latest job
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  wildfly-integration:
    name: 'WildFly Integration Tests'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest ]
        java: ['17', '21']

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven Java ${{ matrix.java }} - ${{ matrix.os }}
        run:  |
          ./mvnw -V clean install -U -B -fae '-Pwildfly' '-T1' '-Pintegration-tests'
      - uses: actions/upload-artifact@v5
        if: failure()
        with:
          name: wildfly-surefire-reports-${{ matrix.os }}-${{ matrix.java }}
          path: '**/surefire-reports/*'
      - uses: actions/upload-artifact@v5
        if: failure()
        with:
          name: wildfly-server-logs-${{ matrix.os }}-${{ matrix.java }}
          path: '**/server.log'

  payara-integration:
    name: 'Payara Integration Tests'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest ]
        java: ['11', '17', '21']

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven Java ${{ matrix.java }} - ${{ matrix.os }}
        run:  |
          ./mvnw -V clean install -U -B -fae '-Ppayara' '-T1' '-Pintegration-tests'
      - uses: actions/upload-artifact@v5
        if: failure()
        with:
          name: paraya-surefire-reports-${{ matrix.os }}-${{ matrix.java }}
          path: '**/surefire-reports/*'
      - uses: actions/upload-artifact@v5
        if: failure()
        with:
          name: paraya-server-logs-${{ matrix.os }}-${{ matrix.java }}
          path: '**/server.log'
